### ISSUE TITLE
request 2.1.0-3

### ISSUE THREAD

**Issue by navels** [webjars/durandal#5]
Can I trouble you to do a snapshot release of the latest?

Thanks,
Lee

**Comment by jamesward** [comment]
I'm not sure what you need.  It looks like `2.1.0` is the latest.

**Comment by navels** [comment]
There is a 2.1.0-2 at webjars.org but it is not up-to-date.

**Comment by jamesward** [comment]
I'm not sure what you mean.  There doesn't seem to be a newer release on http://durandaljs.com/downloads.html

**Comment by navels** [comment]
Any idea how those patch releases (2.1.0-1 and 2.1.0-2) got on webjars?

**Comment by jamesward** [comment]
The `-1` and `-2` were bug fixes to WebJar packaging of the `2.1.0` release.  You can see the whole story in the commit history: https://github.com/webjars/durandal/commits/master

**Comment by navels** [comment]
Got it, thanks for the clarification.
